export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const ACCESS_KEY = 'WrEM52RwbZ8isH3h2qo2D7W4Hd1e8Y8tpbf0mdpYWUI';
export const SECRET_KEY = 'S99nh4yriiZB1OrvVi_MV-QKyOx25yM98QEGByI96K8';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const REDIRECT_URI = 'https://elenasharnina.github.io/gallery/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_photos write_likes read_user';
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';